### ISSUE TITLE
No /var/log/tests/ at test nodes (gluster server) to verify the test result

### ISSUE THREAD

**Issue by kiranfractal** [gluster/distaf#10] opened 2015-02-20 08:34 UTC
I installed and ran distaf against two gluster server and its result is passed it seems but I could not see any gluster related info at the test nodes (gluster server).

I did ssh-copy-id for user fractalio which is not root user.

Do I need to do ssh-copy-id for root user ? 

How to verify that the testcase has been really executed on the test nodes ?

Let me know, if you need any further info.

### config.sh file content:
---------------------------
#export MGMT_NODE="mgmt_node"
export NODES="192.168.1.244"
#export CLIENTS="client0 client1"
export PEERS="192.168.1.245"
#export GM_NODES="gm_master0 gm_master1"
#export GS_NODES="gs_slave0 gs_slave1"

### development1@development1-ME051 ~/Documents/distaf $ sudo python main.py 
------
test_gluster_basic_test (__main__.gluster_tests) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK

### development1@development1-ME051 ~/Documents/distaf $ tail -f /var/log/tests/distaf_tests.log
-------
2015-02-20 13:49:49,254 INFO gluster_basic_test Testing gluster volume create and mounting
^C

**Comment by msvbhat** [comment] 2015-02-27 13:23
Hi Kiran,

Thanks for reporting the issue.

For distaf, you can do ssh-copy-id to any remote_user@. You should export the variable 'REMOTE_USER'
export REMOTE_USER="fractalio"

But glusterd needs to be started as a root user. Also all gluster commands needs to be run as a root user, so to run gluster tests, you will need 'root' access anyway.

The logs will be maintained in the management node (it can be server node as well). By default it will be at /var/log/tests/distaf.log. If you don't get any logs there, it might be an issue. Let me take a look once. You can change the default logs using
export LOG_FILE="/path/to/new/logfile.log"

Thanks
MS

**Comment by kiranfractal** [comment] 2015-02-27 13:39
Hi,

I think the testcase has to fail with clear information saying you need to login as root user.

Thanks,
Kiran.

**Comment by msvbhat** [comment] 2015-02-27 14:34
I was depending on the "glusterd" to error out with proper message. Looks like it's better to handle it within the framework. Will send in a patch soon.

There will be no logs maintained in the gluster nodes. The logs will be present in the /var/log/tests/distaf_tests.log of management node (the machine from where tests are run).

Thanks, I will check why the log entries were not generated.

-MS

**Comment by kiranfractal** [comment] 2015-03-02 11:20
Hi,

I updated to current master commit. Now using root user " export REMOTE_USER="root"". Still  getting only INFO information regarding Test.

Please guide me to resolve the issue.

Below is output from log file from Management node:
---------------------------------
development1@development1-ME051 ~/Documents/distaf $ sudo tail -f /var/log/tests/distaf_tests.log 
2015-02-20 14:12:19,653 INFO gluster_basic_test Testing gluster volume create and mounting
2015-02-20 14:14:12,671 INFO gluster_basic_test Testing gluster volume create and mounting
2015-02-27 19:02:44,522 INFO gluster_basic_test Testing gluster volume create and mounting
2015-02-27 19:06:38,136 INFO gluster_basic_test Testing gluster volume create and mounting
2015-03-02 16:34:36,585 INFO gluster_basic_test Testing gluster volume create and mounting
2015-03-02 16:39:06,022 INFO gluster_basic_test Testing gluster volume create and mounting

Config.sh file contents:
-------------------
export MGMT_NODE="development1-ME051"
export NODES="192.168.1.244"
#export CLIENTS="client0 client1"
export PEERS="192.168.1.245"
#export GM_NODES="gm_master0 gm_master1"
#export GS_NODES="gs_slave0 gs_slave1"

 I also tried below combination and still no luck
------------------------
export MGMT_NODE="development1-ME051"
export NODES="192.168.1.244 192.168.1.245"
#export CLIENTS="client0 client1"
#export PEERS="192.168.1.245"
#export GM_NODES="gm_master0 gm_master1"
#export GS_NODES="gs_slave0 gs_slave1"

Thanks.

**Comment by msvbhat** [comment] 2015-03-02 14:35
Kiran,

I will push the create_passwdless_shh.sh in some time. That should help you in setting up the systems for test run.

Can set the log level to DEBUG and run again?

export LOG_LEVEL='DEBUG'
and then run "python main.py"

This should work once all the required variable are exported. Please let me know what's the output.

**Comment by kiranfractal** [comment] 2015-03-03 09:46
Still I am getting the same error.

2015-03-02 16:34:36,585 INFO gluster_basic_test Testing gluster volume create and mounting
2015-03-02 16:39:06,022 INFO gluster_basic_test Testing gluster volume create and mounting
2015-03-02 16:45:47,862 INFO gluster_basic_test Testing gluster volume create and mounting
2015-03-03 15:08:53,280 INFO gluster_basic_test Testing gluster volume create and mounting
2015-03-03 15:13:17,277 INFO gluster_basic_test Testing gluster volume create and mounting
2015-03-03 15:14:08,248 INFO gluster_basic_test Testing gluster volume create and mounting

**Comment by kirantpatil** [comment] 2015-09-02 06:50
@msvbhat, please feel free to close this issue, since I no more associated with fractalio.

**Comment by msvbhat** [comment] 2015-09-02 08:59
I haven't been able to reproduce this issue in my environment. So I will close the issue now. Will reopen, if faced again.

**Closed by msvbhat** 2015-09-02 08:59 UTC
